### ISSUE TITLE
Cannot disable warnings/output from no-duplicate-headings rule

### ISSUE THREAD

**Issue by GrayedFox** [wooorm/remark-message-control#7]
Hi there, 

I understand this functionality is bundled into remark-lint, which is where I found the documentation, but I also confirmed the syntax/style inside this repository (which remark-lint depends on) and so thought it would be better to post here.

The relevant part of my `package.json` looks like this:

```
    "remark-cli": "^5.0.0",
    "remark-lint": "^6.0.2",
    "remark-lint-first-heading-level": "^1.1.2",
    "remark-lint-linebreak-style": "^1.0.2",
    "remark-lint-no-empty-url": "^1.0.3",
    "remark-lint-no-heading-indent": "^1.0.2",
    "remark-lint-no-missing-blank-lines": "^1.0.2",
    "remark-lint-no-paragraph-content-indent": "^1.0.4",
    "remark-lint-no-tabs": "^1.0.2",
    "remark-preset-lint-markdown-style-guide": "^2.1.2",
    "remark-preset-lint-recommended": "^3.0.2",
    "remark-stringify": "^5.0.0"
```

Inside the markdown file that I want to suppress the duplicate header warnings for, I have this line at the very top:

`<!--lint disable no-duplicate-headings-->`

But despite this I still get all the warnings for duplicate headings. The level is set to "warn" (not to error) on instances of duplicate headings, which is bundled into the preset-lint-recommended package.

**Comment by wooorm** [comment]
@GrayedFox Hey, thanks for the issue!

How are you running remark?

**Comment by GrayedFox** [comment]
Via the `package.json` scripts property:

```
  "scripts": {
    "test": "yarn docs:lint:en && yarn docs:lint:de",
    "docs:dev": "vuepress dev docs",
    "docs:build": "vuepress build docs",
    "docs:lint:en": "remark ./docs/en/*/",
    "docs:lint:de": "remark ./docs/de/*/",
    "heroku-postbuild": "yarn docs:build"
  }
```

And then from the console: `yarn docs:lint:en` or `yarn docs:lint:de`

**Comment by wooorm** [comment]
But, where is your configuration 🤔

**Comment by GrayedFox** [comment]
Oh! Right - also in the `package.json` file:

```
  "remarkConfig": {
    "plugins": {
      "lint-code-block-style": [
        "error",
        "fenced"
      ],
      "lint-emphasis-marker": [
        "error",
        "*"
      ],
      "lint-file-extension": [
        "error",
        "md"
      ],
      "lint-final-definition": [
        "error"
      ],
      "lint-final-newline": [
        "error"
      ],
      "lint-first-heading-level": [
        "error",
        1
      ],
      "lint-heading-increment": [
        "error",
        1
      ],
      "lint-heading-style": [
        "error",
        "atx"
      ],
      "lint-linebreak-style": [
        "error",
        "unix"
      ],
      "lint-maximum-line-length": [
        "error",
        80
      ],
      "lint-no-consecutive-blank-lines": [
        "error"
      ],
      "lint-no-duplicate-definitions": [
        "error"
      ],
      "lint-no-duplicate-headings": [
        "warn"
      ],
      "lint-no-emphasis-as-heading": [
        "warn"
      ],
      "lint-no-empty-url": [
        "error"
      ],
      "lint-no-file-name-irregular-characters": [
        "error"
      ],
      "lint-no-file-name-mixed-case": [
        "error"
      ],
      "lint-no-heading-content-indent": [
        "error"
      ],
      "lint-no-heading-indent": [
        "error"
      ],
      "lint-no-heading-punctuation": [
        "error"
      ],
      "lint-no-inline-padding": [
        "error"
      ],
      "lint-no-literal-urls": [
        "error"
      ],
      "lint-no-missing-blank-lines": [
        "error"
      ],
      "lint-no-paragraph-content-indent": [
        "error"
      ],
      "lint-no-shell-dollars": [
        "error"
      ],
      "lint-no-tabs": [
        "error"
      ],
      "lint-no-unused-definitions": [
        "error"
      ],
      "lint-ordered-list-marker-style": [
        "error",
        "."
      ],
      "lint-strong-marker": [
        "error",
        "*"
      ],
      "lint-table-cell-padding": [
        "error",
        "padded"
      ],
      "lint-table-pipe-alignment": [
        "error"
      ],
      "lint-table-pipes": [
        "error"
      ],
      "lint-unordered-list-marker-style": [
        "error",
        "-"
      ]
    },
    "settings": {
      "emphasis": "*",
      "strong": "*",
      "incrementListMarker": false
    }
  }
}
```

**Comment by wooorm** [comment]
It looks like you installed the `remark-lint` plugin, but it isn’t passed to remark. You should be able to do

```diff
    "plugins": {
+     "lint",
      "lint-code-block-style": [
        "error",
        "fenced"
      ],
```

...to make everything work!

**Comment by GrayedFox** [comment]
Hmm - that would be invalid JSON my friend? Although I like that code highlighting trick!

I tried adding `"lint",` (with comma - lint immediately fails due to badly formatted JSON), and also tried adding `"lint": {},` - but I still get the warnings. I tried placing all the rules inside `"lint": { ... }` object but then the rules are not passed at all.

**Comment by wooorm** [comment]
`"lint": null`, (or `"lint": {}`) sorry! That should work.

>  but I still get the warnings.

Weird, that shouldn’t happen!

> I tried placing all the rules inside "lint": { ... } object but then the rules are not passed at all.

Yeah that’s not it!

**Comment by GrayedFox** [comment]
Yay!!! 

Passing `"lint": null` fixes it! Also I just double checked and I must have removed the ignore comment when I tested it with `"lint": {}` because passing an empty object also works.

Thank you! 

It is a little strange however that the rules and even fixing files with remark-lint works without that line. Makes me wonder what other little features were secretly disabled this whole time... :woman_cartwheeling:

**Comment by wooorm** [comment]
yeah remark-lint itself doesn’t do anything, other than comment configuration. It used to do much more, and may do more in the future too!

Happy linting!
